#! /bin/bash

for i in `find levels/`; do
    if [ ! -d $i ]; then
	java -Xmx256m -jar dist/skbsolver.jar $i DFS > sol
	echo "Level $i"
	cat sol
	cat sol | tail -n 2 | head -n 1 > resol
	./check $i resol
    fi
done;
